// Write your formula below, select 'Run' to try it out. When ready, select 'Update model' to add the measure to your model.
DEFINE
	MEASURE '.measures'[New Measure] = COUNTROWS('.measures')

EVALUATE
	SUMMARIZECOLUMNS(
		"New Measure", [New Measure]
	)