table order_payments
	lineageTag: 1d750a8e-18a3-4c06-bc5a-6f28151ea0f2

	column order_id
		dataType: string
		lineageTag: 6a6018ec-4b47-4ac8-b395-ec19a0beb428
		summarizeBy: none
		sourceColumn: order_id

		annotation SummarizationSetBy = Automatic

	column payment_sequential
		dataType: int64
		formatString: 0
		lineageTag: a7131a1b-aa9a-4160-9dac-bed8d08b4bde
		summarizeBy: sum
		sourceColumn: payment_sequential

		annotation SummarizationSetBy = Automatic

	column payment_type
		dataType: string
		lineageTag: f9ac6637-9ae8-41e6-9349-c4b4e17b415c
		summarizeBy: none
		sourceColumn: payment_type

		annotation SummarizationSetBy = Automatic

	column payment_installments
		dataType: int64
		formatString: 0
		lineageTag: 75da17dd-d82d-4d36-a799-fc0194c666da
		summarizeBy: sum
		sourceColumn: payment_installments

		annotation SummarizationSetBy = Automatic

	column payment_value
		dataType: decimal
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		lineageTag: c85846fb-22b1-4d1e-89e2-88d1f9695546
		summarizeBy: sum
		sourceColumn: payment_value

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	partition order_payments = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\mariu\OneDrive\data-analyst\brazilian-ecommerce\csv\olist_order_payments_dataset.csv"),[Delimiter=",", Columns=5, Encoding=1250, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"order_id", type text}, {"payment_sequential", Int64.Type}, {"payment_type", type text}, {"payment_installments", Int64.Type}, {"payment_value", type text}}),
				    #"Replaced Value" = Table.ReplaceValue(#"Changed Type",".",",",Replacer.ReplaceText,{"payment_value"}),
				    #"Changed Type with Locale" = Table.TransformColumnTypes(#"Replaced Value", {{"payment_value", Currency.Type}}, "pt-BR"),
				    #"Sorted Rows" = Table.Sort(#"Changed Type with Locale",{{"order_id", Order.Ascending}}),
				    #"Filtered Rows" = Table.SelectRows(#"Sorted Rows", each true),
				    #"Removed Duplicates" = Table.Distinct(#"Filtered Rows")
				in
				    #"Removed Duplicates"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

